In [194]:
import sys
import os
import datetime
import pandas as pd
import pandas_ta as ta
sys.path.append(r"C:\Users\DeGenOne\degen-money-backtest")
import warnings
warnings.filterwarnings('ignore')

In [188]:
from backtest.data.data import DataProducer, get_all_expiry_info, fetch_options_data_and_resample, get_expiry_dates, get_expiry_comp_dict
from backtest.strategy.strategy import Strategy
from backtest.utils import utils
from backtest.opt_backtest.opt_backtest import OptBacktest

In [189]:
instrument = "BANKNIFTY"
start_date = "2019-01-01"
end_date = "2019-12-31"
timeframe = "1min"
data = DataProducer(instrument, start_date, end_date, timeframe)

In [190]:
df = data.resampled_historical_df
df["day"] = df["date"].dt.date
df = df[df["date"].dt.year == 2019]
expiry_dates = data.bnf_expiry_dates_list
expiry_comp_dict = data.bnf_expiry_comp_dict
filtered_expiry = []
for x in expiry_dates:
    if x.year == 2019:
        filtered_expiry.append(x)
filtered_df = df[df['date'].dt.date.isin(filtered_expiry)]
filtered_df.reset_index(drop=True, inplace=True)
filtered_df = filtered_df.groupby("day")
ce_options_data = []
pe_options_data = []

track_time = utils.str_to_time_obj("9:20")

for day, day_df in filtered_df:
    close = day_df[day_df["date"].dt.time == track_time]["close"]
    atm = int(round(close, -2))
    ce_otm1 = atm + 100
    pe_otm1 = atm - 100
    expiry_comp = expiry_comp_dict[day]
    ce_opt_symbol = f"BANKNIFTY{expiry_comp}{ce_otm1}CE"
    pe_opt_symbol = f"BANKNIFTY{expiry_comp}{pe_otm1}PE"
    ce_symbol_data = fetch_options_data_and_resample(ce_opt_symbol, day, day, "5min")
    ce_symbol_data = ce_symbol_data.rename(columns={f"{ce_opt_symbol}_close":"close",
                                                 f"{ce_opt_symbol}_open":"open",
                                                  f"{ce_opt_symbol}_high": "high",
                                                    f"{ce_opt_symbol}_low":"low",
                                                    f"{ce_opt_symbol}_volume":"volume"})
    pe_symbol_data = fetch_options_data_and_resample(pe_opt_symbol, day, day, "5min")
    pe_symbol_data = ce_symbol_data.rename(columns={f"{pe_opt_symbol}_close":"close",
                                                 f"{pe_opt_symbol}_open":"open",
                                                  f"{pe_opt_symbol}_high": "high",
                                                    f"{pe_opt_symbol}_low":"low",
                                                    f"{pe_opt_symbol}_volume":"volume"})
    ce_options_data.append(ce_symbol_data)
    pe_options_data.append(pe_symbol_data)
ce_options_df = pd.concat(ce_options_data, ignore_index=True)
pe_options_df = pd.concat(ce_options_data, ignore_index=True)

In [197]:
ce_options_df["rsi"] = ta.rsi(ce_options_df["close"], window=14)

                    date   open   high    low  close     volume        rsi
75   2019-01-10 09:15:00  66.60  66.60  38.30  44.60  1360102.0  89.436834
76   2019-01-10 09:20:00  45.00  47.65  34.00  39.15  1163480.0  80.360817
77   2019-01-10 09:25:00  39.50  41.85  31.90  33.75   855060.0  72.509285
78   2019-01-10 09:30:00  33.80  37.00  27.20  29.20   975260.0  66.604352
79   2019-01-10 09:35:00  29.60  29.85  24.25  29.35   955060.0  66.700629
...                  ...    ...    ...    ...    ...        ...        ...
3787 2019-12-19 12:20:00  56.85  62.30  56.75  60.60   472580.0  56.593488
3788 2019-12-19 12:25:00  60.95  61.00  55.15  57.10   256820.0  53.759552
3789 2019-12-19 12:30:00  56.50  61.00  49.25  60.35   505780.0  55.964636
3790 2019-12-19 12:35:00  60.45  60.95  54.90  56.80   393420.0  52.991992
3825 2019-12-26 09:15:00  40.05  44.85  18.25  20.40  1007343.0  52.492604

[1463 rows x 7 columns]